---
- block:
    - name: ensure pip is installed
      apt:
        name: python-pip
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes

  become: yes
  tags:
    - pip